### ISSUE TITLE
a question of export 

### ISSUE THREAD

**Issue by co-LMAI** [camnewnham/Timeline#2]
Something went wrong while combining video frames... (ffmpeg quit with exit code 1)
![bb6f1b0778b78a8a0960b0542501f46](https://github.com/camnewnham/GH_Timeline/assets/57410772/eadeb684-2656-4155-bd25-8e496d48d763)

**Comment by camnewnham** [comment]
Thanks for reporting. Does this happen if you export the frames as jpg or png instead?

**Comment by co-LMAI** [comment]
the problem has been solved,that is caused by the name of the frame file.

**Comment by camnewnham** [comment]
Thanks for posting the solution :)
